service: create-tables

provider:
  name: aws
  runtime: python3.13
  region: us-east-1
  stage: dev
  memorySize: 256
  timeout: 20
  iam:
    role: arn:aws:iam::468251834706:role/LabRole
  httpApi:
    cors: true

resources:
  Resources:
    # Tabla de Empleados
    EmployeeTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: t_employee
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: user_id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: user_id
            KeyType: RANGE

    TokensEmployeeTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: t_tokens_employee_acceso
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: token
            AttributeType: S
        KeySchema:
          - AttributeName: token
            KeyType: HASH

    # Tabla de Productos
    ProductosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: t_product
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: product_id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: product_id
            KeyType: RANGE

    ProductosBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: products-200millas
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders: ["*"]
              AllowedMethods: ["PUT", "GET", "POST", "HEAD"]
              AllowedOrigins: ["*"]
              ExposedHeaders: ["ETag"]

    # Tabla de Usuarios
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: t_users
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: user_id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: user_id
            KeyType: RANGE

    TokensUsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: t_tokens_users_acceso
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: token
            AttributeType: S
        KeySchema:
          - AttributeName: token
            KeyType: HASH
