service: pedidos-seguridad
frameworkVersion: "4"

org: darosv

provider:
  name: aws
  runtime: python3.12
  region: us-east-1   # cambia si tu Learner Lab usa otra región
  stage: dev
  memorySize: 256
  timeout: 30
  iam:
    role: arn:aws:iam::645337731455:role/LabRole
  environment:
    USERS_TABLE: t_usuarios
    TOKENS_TABLE: t_tokens_acceso
    PRODUCTS_TABLE: t_productos
    PRODUCTS_BUCKET: productos-200millas-dev
  httpApi:
    cors: true

functions:
  GetUploadUrl:
    handler: src/productos_get_upload_url.lambda_handler
    events:
      - httpApi:
          method: POST
          path: /productos/upload-url

  CrearProducto:
    handler: src/productos_crear.lambda_handler
    events:
      - httpApi:
          method: POST
          path: /productos/crear
  CrearUsuario:
    handler: src/crear_usuario.lambda_handler
    events:
      - httpApi:
          method: POST
          path: /usuarios/crear

  LoginUsuario:
    handler: src/login_usuario.lambda_handler
    events:
      - httpApi:
          method: POST
          path: /usuarios/login

  ValidarTokenAcceso:
    handler: src/validar_token.lambda_handler
    # sin evento HTTP; la usas internamente desde otras Lambdas si quieres

resources:
  Resources:
    ProductosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: t_productos
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: product_id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: product_id
            KeyType: RANGE

    ProductosBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: productos-200millas-dev
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders: ["*"]
              AllowedMethods: ["PUT","GET"]
              AllowedOrigins: ["*"]
              ExposedHeaders: ["ETag"]
    UsuariosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: t_usuarios
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: user_id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: user_id
            KeyType: RANGE

    TokensTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: t_tokens_acceso
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: token
            AttributeType: S
        KeySchema:
          - AttributeName: token
            KeyType: HASH

custom:
  # En v4 no declares el plugin; esto activa la integración nativa
  pythonRequirements:
    slim: true
