service: service-clientes

provider:
  name: aws
  runtime: python3.13
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  memorySize: 256
  timeout: 20
  iam:
    role: arn:aws:iam::${env:AWS_ACCOUNT_ID}:role/LabRole
  httpApi:
    cors: true
  environment:
    TABLE_PEDIDOS: ${env:TABLE_PEDIDOS}
    TOKENS_TABLE_USERS: ${env:TABLE_TOKENS_USUARIOS}
    VALIDAR_TOKEN_LAMBDA_NAME: ${env:VALIDAR_TOKEN_LAMBDA_NAME}
    EVENT_BUS_NAME: default

functions:
  CreatePedido:
    handler: pedido_create.lambda_handler
    events:
      - httpApi:
          method: POST
          path: /pedido/create

  GetPedidoEstado:
    handler: estado_pedido.lambda_handler
    events:
      - httpApi:
          method: GET
          path: /pedido/status

  triggerConfirmarCliente:
    handler: trigger_confirmar_cliente.handler
    events:
      - httpApi:
          path: /pedido/confirmar
          method: POST
    description: "Trigger ConfirmarPedidoCliente event when customer confirms receipt"
