service: service-employees

provider:
  name: aws
  runtime: python3.13
  region: us-east-1
  memorySize: 256
  timeout: 20
  iam:
    role: arn:aws:iam::645337731455:role/LabRole
  environment:
    EMPLOYEE_TABLE: t_employee
    TOKENS_EMPLOYEE_TABLE: t_tokens_employee_acceso
  layers:
    - ${cf:millas-dependencias-dev.PythonDependenciesLayerExport}  
  httpApi:
    cors: true

functions:
  RegisterEmployee:
    handler: register_employee.lambda_handler
    events:
      - httpApi:
          method: POST
          path: /employees/register
          cors: true
          integration: lambda

  LoginEmployee:
    handler: login_employee.lambda_handler
    events:
      - httpApi:
          method: POST
          path: /employees/login
          cors: true
          integration: lambda