service: service-employees

provider:
  name: aws
  runtime: python3.13
  region: us-east-1
  memorySize: 256
  timeout: 20
  iam:
    role: arn:aws:iam::468251834706:role/LabRole
  environment:
    EMPLOYEE_TABLE: t_employee
    TOKENS_EMPLOYEE_TABLE: t_tokens_employee_acceso
  httpApi:
    cors: true

functions:
  RegisterEmployee:
    handler: employees.register_employee.lambda_handler
    events:
      - httpApi:
          method: POST
          path: /employees/register
  LoginEmployee:
    handler: employees.login_employee.lambda_handler
    events:
      - httpApi:
          method: POST
          path: /employees/login
