service: service-users

provider:
  name: aws
  runtime: python3.13
  region: us-east-1
  memorySize: 256
  timeout: 20
  iam:
    role: arn:aws:iam::468251834706:role/LabRole
  environment:
    USERS_TABLE: t_users
    TOKENS_TABLE_USERS: t_tokens_users_acceso
  httpApi:
    cors: true
    
functions:
  RegisterUser:
    handler: users.register_user.lambda_handler
    events:
      - httpApi:
          method: POST
          path: /users/register
  LoginUsuario:
    handler: users.login_usuario.lambda_handler
    events:
      - httpApi:
          method: POST
          path: /users/login
  ValidarUserTokenAcceso:
    handler: users.validar_token_users.lambda_handler
