service: service-users

provider:
  name: aws
  runtime: python3.13
  region: us-east-1
  memorySize: 256
  timeout: 20
  iam:
    role: arn:aws:iam::${env:AWS_ACCOUNT_ID}:role/LabRole
  environment:
    USERS_TABLE: ${env:TABLE_USUARIOS}
    TOKENS_TABLE_USERS: ${env:TABLE_TOKENS}
  httpApi:
    cors: true
    
functions:
  RegisterUser:
    handler: register_user.lambda_handler
    events:
      - httpApi:
          method: POST
          path: /users/register
          cors: true
          integration: lambda

  LoginUsuario:
    handler: login_user.lambda_handler
    events:
      - httpApi:
          method: POST
          path: /users/login
          cors: true
          integration: lambda
                    
  ValidarUserTokenAcceso:
    handler: validar_token_users.lambda_handler
